# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 960755a89a97873297eb2ef336bfe1987dbd56c402c1d62b8389ef535d670a68f2a9b21ccc9843dcce503f498f83c0190af85bb2b4ee0b80e7e8e03555bbed1c

test:
  secret_key_base: e6f09daa70f812aa92dc7d351ae85a4e33eebdb5d9901bc7069f05a4719ee8cd9a27a9298af1759f96b8af619e4ed5541777b4681bdcf0133e65e024e4b75ebe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
